#!/usr/bin/env python3
"""Bundle PORE's own icons (icons/modern/<key>.svg) into one sprite: icons/sprite.svg

Every equipment item (key i<id>) and charm (key c<id>) must have a drawing in icons/modern/;
equipment icons are generated by tools/modern_icons.py, charms are drawn by hand.
Missing drawings get a neutral placeholder symbol and are reported.

Usage:
    python tools/make_svg.py
"""
from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "items.json"
MODERN = ROOT / "icons" / "modern"
SPRITE = ROOT / "icons" / "sprite.svg"

PLACEHOLDER = ('<rect x="10" y="10" width="44" height="44" rx="12" fill="#3c3c56" stroke="#0a0a12" stroke-width="2"/>'
               '<path d="M32 20 L40 32 L32 44 L24 32 Z" fill="#8b7cff"/>')


def symbol(key: str, svg: str) -> str:
    """Turn a standalone SVG into a <symbol>, namespacing ids so gradients cannot collide."""
    svg = re.sub(r"<\?xml[^>]*\?>|<!--.*?-->", "", svg, flags=re.S).strip()
    open_tag = re.match(r"<svg\b[^>]*>", svg, flags=re.S)
    if not open_tag:
        raise SystemExit(f"{key}: not an <svg> document")
    view = re.search(r'viewBox="([^"]+)"', open_tag.group(0))
    viewbox = view.group(1) if view else "0 0 64 64"
    inner = svg[open_tag.end():svg.rfind("</svg>")]
    inner = re.sub(r'\bid="([^"]+)"', lambda m: f'id="{key}-{m.group(1)}"', inner)
    inner = re.sub(r"url\(#([^)]+)\)", lambda m: f"url(#{key}-{m.group(1)})", inner)
    inner = re.sub(r'href="#([^"]+)"', lambda m: f'href="#{key}-{m.group(1)}"', inner)
    return f'<symbol id="{key}" viewBox="{viewbox}">{inner}</symbol>'


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    keys = [f"i{it['id']}" for it in data["items"]] + [f"c{ch['id']}" for ch in data.get("charms", [])]
    symbols, missing = [], []
    for key in keys:
        path = MODERN / f"{key}.svg"
        if path.exists():
            symbols.append(symbol(key, path.read_text(encoding="utf-8")))
        else:
            missing.append(key)
            symbols.append(f'<symbol id="{key}" viewBox="0 0 64 64">{PLACEHOLDER}</symbol>')
    sprite = '<svg xmlns="http://www.w3.org/2000/svg" style="display:none">' + "".join(symbols) + "</svg>"
    SPRITE.write_text(sprite, encoding="utf-8")
    print(f"wrote {SPRITE.relative_to(ROOT)}: {len(keys) - len(missing)}/{len(keys)} icons ({len(sprite) // 1024} KB)")
    if missing:
        print("missing drawings (placeholder used):", ", ".join(missing))


if __name__ == "__main__":
    main()
