// PORE pixel icons: every HD drawing (icons/modern/<key>.svg) turned into pixel art by pixelkit
// (tools/pixelkit/, see its README), written as an editable text grid icons/pixel-src/<key>.txt, then
// rendered to icons/pixel/ and the sprite.
//
// Hand edits: a grid without the "generated" line is never overwritten, so any icon can be finished by
// hand in its .txt file (one character per pixel, colours listed above the grid).
//
//   node tools/pixelart.mjs            compile missing/generated grids, then render all
//   node tools/pixelart.mjs --render   only render the grids to SVG

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { pixelKit } from './pixelkit/pixelkit.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const HD = path.join(ROOT, 'icons', 'modern');
const SRC = path.join(ROOT, 'icons', 'pixel-src');
const OUT = path.join(ROOT, 'icons', 'pixel');
const SPRITE = path.join(ROOT, 'icons', 'sprite-pixel.svg');
const MARK = '# generated by tools/pixelart.mjs (delete this line to keep hand edits)';
// PORE's look: 32x32, strong colour, dithered shading, ambient occlusion and a soft cast shadow (the kit's defaults)
const kit = pixelKit({ size: 32, vivid: 1.8, contrast: 1.16, dither: true, ao: true, shadow: 0.32, mark: MARK });
const { compile, toTxt, fromTxt, toSvg } = kit, N = kit.options.size;
// icons whose fire flickers (pixelkit's palette cycling): Torch and Lamp of Seeking ('flame'), the Lantern's light ('pulse'), Jack-o'-Lantern's face ('glow')
const ANIMATE = { i3076: 'flame', i3077: 'pulse', i23553: 'flame', i22020: 'glow' };

/* ------------------------------------------------------------------ main */
const names = {};
try {
  const db = JSON.parse(readFileSync(path.join(ROOT, 'data', 'items.json'), 'utf8'));
  for (const it of db.items) names['i' + it.id] = it.name;
  for (const c of db.charms || []) names['c' + c.id] = c.name;
  for (const g of db.goods || []) names['i' + g.id] = g.name;
} catch (e) { /* names are only comments */ }

mkdirSync(SRC, { recursive: true });
const keys = readdirSync(HD).filter(f => f.endsWith('.svg')).map(f => f.replace(/\.svg$/, '')).sort();
let compiled = 0, kept = 0;
if (!process.argv.includes('--render')) {
  const only = process.argv.includes('--only') ? new Set(process.argv[process.argv.indexOf('--only') + 1].split(',')) : null;
  for (const k of keys) {
    if (only && !only.has(k)) continue;
    const file = path.join(SRC, k + '.txt');
    if (existsSync(file) && !readFileSync(file, 'utf8').includes(MARK)) { kept++; continue; }
    writeFileSync(file, toTxt(names[k] || k, compile(readFileSync(path.join(HD, k + '.svg'), 'utf8'))));
    compiled++;
  }
}
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const symbols = [];
for (const k of keys) {
  const file = path.join(SRC, k + '.txt');
  if (!existsSync(file)) continue;
  const svg = toSvg(fromTxt(readFileSync(file, 'utf8')), ANIMATE[k]);
  writeFileSync(path.join(OUT, k + '.svg'), svg + '\n');
  symbols.push(`<symbol id="${k}" viewBox="0 0 ${N} ${N}">${svg.slice(svg.indexOf('>') + 1, svg.lastIndexOf('</svg>'))}</symbol>`);
}
const sprite = `<svg xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges" style="display:none">${symbols.join('')}</svg>`;
writeFileSync(SPRITE, sprite);
console.log(`pixel icons: compiled ${compiled}, kept ${kept} hand-edited, rendered ${symbols.length} at ${N}x${N} (${Math.round(sprite.length / 1024)} KB sprite)`);
