// PORE pixel icons (24x24): every HD drawing (icons/modern/<key>.svg) compiled element by element into
// pixel art, written as an editable text grid icons/pixel-src/<key>.txt, then rendered to icons/pixel/.
//
// Each SVG element becomes its own pixel region in paint order, so the pixel icon keeps the HD icon's
// layout, orientation and colours. A region is shaded from its own gradient ramp (light on its top/left
// rim, shadow on its bottom/right rim), dark outline strokes are dropped and one clean 1-pixel outline is
// drawn around the whole silhouette. Small details (gems, eyes, studs) always keep at least one pixel.
//
// Hand edits: a grid without the "generated" line is never overwritten, so any icon can be finished by
// hand in its .txt file (one character per pixel, colours listed above the grid).
//
//   node tools/pixelart.mjs            compile missing/generated grids, then render all
//   node tools/pixelart.mjs --render   only render the grids to SVG

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const HD = path.join(ROOT, 'icons', 'modern');
const SRC = path.join(ROOT, 'icons', 'pixel-src');
const OUT = path.join(ROOT, 'icons', 'pixel');
const SPRITE = path.join(ROOT, 'icons', 'sprite-pixel.svg');
const N = 32, U = 64 / N;                 // grid size (32x32: the sweet spot between pixel look and detail), SVG units per pixel
const MARK = '# generated by tools/pixelart.mjs (delete this line to keep hand edits)';

/* ------------------------------------------------------------------ colour helpers */
const hex = h => { h = h.replace('#', ''); if (h.length === 3) h = [...h].map(c => c + c).join(''); return [0, 2, 4].map(i => parseInt(h.slice(i, i + 2), 16)); };
const toHex = c => '#' + c.map(v => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0')).join('');
const lum = c => (0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]) / 255;
const mix = (a, b, t) => a.map((v, i) => v + (b[i] - v) * t);

/* ------------------------------------------------------------------ geometry */
const I = [1, 0, 0, 1, 0, 0];
const mul = (m, n) => [m[0] * n[0] + m[2] * n[1], m[1] * n[0] + m[3] * n[1], m[0] * n[2] + m[2] * n[3], m[1] * n[2] + m[3] * n[3],
  m[0] * n[4] + m[2] * n[5] + m[4], m[1] * n[4] + m[3] * n[5] + m[5]];
const ap = (m, [x, y]) => [m[0] * x + m[2] * y + m[4], m[1] * x + m[3] * y + m[5]];
function parseTransform(t) {
  let m = I;
  for (const [, fn, args] of (t || '').matchAll(/(\w+)\(([^)]*)\)/g)) {
    const a = args.split(/[\s,]+/).filter(Boolean).map(Number);
    if (fn === 'translate') m = mul(m, [1, 0, 0, 1, a[0], a[1] || 0]);
    else if (fn === 'scale') m = mul(m, [a[0], 0, 0, a[1] ?? a[0], 0, 0]);
    else if (fn === 'rotate') {
      const r = a[0] * Math.PI / 180, c = Math.cos(r), s = Math.sin(r), cx = a[1] || 0, cy = a[2] || 0;
      m = mul(m, [1, 0, 0, 1, cx, cy]); m = mul(m, [c, s, -s, c, 0, 0]); m = mul(m, [1, 0, 0, 1, -cx, -cy]);
    }
  }
  return m;
}
// path -> list of subpaths { pts, closed }
function flattenPath(d) {
  const toks = d.match(/[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?/g) || [];
  const subs = []; let cur = null, x = 0, y = 0, sx = 0, sy = 0, i = 0, cmd = '';
  const num = () => Number(toks[i++]);
  const push = p => cur.pts.push(p);
  while (i < toks.length) {
    if (/[A-Za-z]/.test(toks[i])) cmd = toks[i++];
    if (cmd === 'M') { x = num(); y = num(); cur = { pts: [[x, y]], closed: false }; subs.push(cur); sx = x; sy = y; cmd = 'L'; }
    else if (cmd === 'L') { x = num(); y = num(); push([x, y]); }
    else if (cmd === 'H') { x = num(); push([x, y]); }
    else if (cmd === 'V') { y = num(); push([x, y]); }
    else if (cmd === 'C') {
      const x1 = num(), y1 = num(), x2 = num(), y2 = num(), x3 = num(), y3 = num();
      for (let k = 1; k <= 12; k++) { const t = k / 12, u = 1 - t; push([u * u * u * x + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t * t * t * x3, u * u * u * y + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t * t * t * y3]); }
      x = x3; y = y3;
    } else if (cmd === 'Q') {
      const x1 = num(), y1 = num(), x2 = num(), y2 = num();
      for (let k = 1; k <= 10; k++) { const t = k / 10, u = 1 - t; push([u * u * x + 2 * u * t * x1 + t * t * x2, u * u * y + 2 * u * t * y1 + t * t * y2]); }
      x = x2; y = y2;
    } else if (cmd === 'A') {
      const rx = num(), ry = num(), rotd = num(), large = num(), sweep = num(), x2 = num(), y2 = num();
      for (const p of arcPoints(x, y, rx, ry, rotd, large, sweep, x2, y2)) push(p);
      x = x2; y = y2;
    } else if (cmd === 'Z' || cmd === 'z') { if (cur) { cur.closed = true; x = sx; y = sy; } cmd = ''; }
    else i++;
  }
  return subs;
}
function arcPoints(x1, y1, rx, ry, phiDeg, fa, fs, x2, y2) {
  const phi = phiDeg * Math.PI / 180, cp = Math.cos(phi), sp = Math.sin(phi);
  const dx = (x1 - x2) / 2, dy = (y1 - y2) / 2, x1p = cp * dx + sp * dy, y1p = -sp * dx + cp * dy;
  let lam = x1p * x1p / (rx * rx) + y1p * y1p / (ry * ry); if (lam > 1) { rx *= Math.sqrt(lam); ry *= Math.sqrt(lam); }
  const sign = fa === fs ? -1 : 1;
  const co = sign * Math.sqrt(Math.max(0, (rx * rx * ry * ry - rx * rx * y1p * y1p - ry * ry * x1p * x1p) / (rx * rx * y1p * y1p + ry * ry * x1p * x1p)));
  const cxp = co * rx * y1p / ry, cyp = -co * ry * x1p / rx;
  const cx = cp * cxp - sp * cyp + (x1 + x2) / 2, cy = sp * cxp + cp * cyp + (y1 + y2) / 2;
  const ang = (ux, uy, vx, vy) => Math.atan2(ux * vy - uy * vx, ux * vx + uy * vy);
  const t1 = ang(1, 0, (x1p - cxp) / rx, (y1p - cyp) / ry);
  let dt = ang((x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry);
  if (!fs && dt > 0) dt -= 2 * Math.PI; else if (fs && dt < 0) dt += 2 * Math.PI;
  const out = [];
  for (let k = 1; k <= 16; k++) { const t = t1 + dt * k / 16; out.push([cx + rx * Math.cos(t) * cp - ry * Math.sin(t) * sp, cy + rx * Math.cos(t) * sp + ry * Math.sin(t) * cp]); }
  return out;
}
const ellipsePts = (cx, cy, rx, ry) => Array.from({ length: 48 }, (_, k) => [cx + rx * Math.cos(k * Math.PI / 24), cy + ry * Math.sin(k * Math.PI / 24)]);
function rectPts(x, y, w, h, rx) {
  rx = Math.min(rx || 0, w / 2, h / 2);
  if (!rx) return [[x, y], [x + w, y], [x + w, y + h], [x, y + h]];
  const pts = [];
  for (const [cx, cy, a0] of [[x + w - rx, y + rx, -90], [x + w - rx, y + h - rx, 0], [x + rx, y + h - rx, 90], [x + rx, y + rx, 180]])
    for (let k = 0; k <= 6; k++) { const a = (a0 + k * 15) * Math.PI / 180; pts.push([cx + rx * Math.cos(a), cy + rx * Math.sin(a)]); }
  return pts;
}
function insideFill(subs, x, y) {        // even-odd over every subpath (open ones are closed implicitly)
  let c = false;
  for (const { pts } of subs) for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    const [xi, yi] = pts[i], [xj, yj] = pts[j];
    if ((yi > y) !== (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi) c = !c;
  }
  return c;
}
function nearStroke(subs, x, y, r) {
  const r2 = r * r;
  for (const { pts, closed } of subs) {
    const n = pts.length, segs = closed ? n : n - 1;
    for (let i = 0; i < segs; i++) {
      const [ax, ay] = pts[i], [bx, by] = pts[(i + 1) % n];
      const vx = bx - ax, vy = by - ay, L = vx * vx + vy * vy;
      let t = L ? ((x - ax) * vx + (y - ay) * vy) / L : 0; t = Math.max(0, Math.min(1, t));
      const dx = ax + t * vx - x, dy = ay + t * vy - y;
      if (dx * dx + dy * dy <= r2) return true;
    }
  }
  return false;
}

/* ------------------------------------------------------------------ SVG -> paint ops */
function parseSvg(svg) {
  const grads = {}, ops = [];
  const stack = [{ m: I, op: 1, inh: {} }];
  const INHERIT = ['fill', 'stroke', 'stroke-width'];   // presentation attributes a <g> passes to its children
  let inDefs = 0, curGrad = null, inClip = 0;
  const attrs = s => Object.fromEntries([...s.matchAll(/([a-zA-Z:-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
  for (const [, close, tag, rest, self] of svg.matchAll(/<(\/?)([a-zA-Z]+)([^>]*?)(\/?)>/g)) {
    const a = attrs(rest);
    if (close) {
      if (tag === 'g') stack.pop();
      if (tag === 'defs') inDefs--;
      if (tag === 'clipPath') inClip--;
      if (/Gradient$/.test(tag)) curGrad = null;
      continue;
    }
    if (tag === 'defs') { if (!self) inDefs++; continue; }
    if (tag === 'clipPath') { if (!self) inClip++; continue; }
    if (/Gradient$/.test(tag)) {
      const num = (v, d) => (v == null ? d : String(v).endsWith('%') ? parseFloat(v) / 100 : Number(v));
      curGrad = grads[a.id] = { stops: [], radial: tag === 'radialGradient', user: a.gradientUnits === 'userSpaceOnUse',
        x1: num(a.x1, 0), y1: num(a.y1, 0), x2: num(a.x2, 1), y2: num(a.y2, 0), cx: num(a.cx, 0.5), cy: num(a.cy, 0.5), r: num(a.r, 0.5) };
      if (self) curGrad = null;
      continue;
    }
    if (tag === 'stop') { if (curGrad) curGrad.stops.push([Number(a.offset || 0), hex(a['stop-color'] || '#000')]); continue; }
    if (tag === 'g') {
      const top = stack[stack.length - 1];
      const inh = { ...top.inh };
      for (const k of INHERIT) if (a[k] != null) inh[k] = a[k];
      const g = { m: mul(top.m, parseTransform(a.transform)), op: top.op * Number(a.opacity ?? 1), inh };
      if (!self) stack.push(g);
      continue;
    }
    if (inDefs || inClip || !['path', 'circle', 'ellipse', 'rect'].includes(tag)) continue;
    const top = stack[stack.length - 1];
    for (const k of INHERIT) if (a[k] == null && top.inh[k] != null) a[k] = top.inh[k];
    const m = mul(top.m, parseTransform(a.transform));
    let subs;
    if (tag === 'path') subs = flattenPath(a.d || '');
    else if (tag === 'circle') subs = [{ pts: ellipsePts(+a.cx || 0, +a.cy || 0, +a.r, +a.r), closed: true }];
    else if (tag === 'ellipse') subs = [{ pts: ellipsePts(+a.cx || 0, +a.cy || 0, +a.rx, +a.ry), closed: true }];
    else subs = [{ pts: rectPts(+a.x || 0, +a.y || 0, +a.width, +a.height, +(a.rx || a.ry || 0)), closed: true }];
    const raw = subs.flatMap(s => s.pts);
    const box = [Math.min(...raw.map(p => p[0])), Math.min(...raw.map(p => p[1])), Math.max(...raw.map(p => p[0])), Math.max(...raw.map(p => p[1]))];
    subs = subs.map(s => ({ pts: s.pts.map(p => ap(m, p)), closed: s.closed }));
    const scale = Math.sqrt(Math.abs(m[0] * m[3] - m[1] * m[2]));
    const op = top.op * Number(a.opacity ?? 1);
    ops.push({ tag, d: a.d || `${tag}${a.cx}${a.cy}${a.r}${a.rx}${a.x}${a.y}`, subs, fill: a.fill ?? '#000', stroke: a.stroke || 'none',
      sw: Number(a['stroke-width'] || 1) * scale, op, m, box });
  }
  const ramp = paint => {
    if (!paint || paint === 'none') return null;
    const g = paint.match(/url\(#([^)]+)\)/);
    if (g) {
      const G = grads[g[1]] || { stops: [[0, [128, 128, 128]]] };
      const st = G.stops.length ? G.stops : [[0, [128, 128, 128]]];
      const at = t => st.reduce((b, s) => (Math.abs(s[0] - t) < Math.abs(b[0] - t) ? s : b))[1];
      return { hi: st[0][1], mid: at(0.5), lo: st[st.length - 1][1], grad: true, G };
    }
    const c = hex(paint);
    return { hi: c, mid: c, lo: c, grad: false };
  };
  // turn elements into paint layers
  const layers = [];
  ops.forEach((o, i) => {
    const fill = ramp(o.fill), stroke = ramp(o.stroke);
    const inkOf = s => (s && lum(s.mid) < 0.35 ? s.mid : null);
    if (fill && o.op >= 0.3) layers.push({ kind: 'fill', subs: o.subs, ramp: fill, ink: inkOf(stroke), op: o.op, rimmed: !!inkOf(stroke) && o.sw >= 1.2, m: o.m, box: o.box });
    if (stroke && o.sw > 0) {
      const dark = lum(stroke.mid) < 0.3;
      if (fill && dark) return;                                   // a shape's outline: redrawn later
      const next = ops[i + 1];
      if (!fill && dark && next && next.d === o.d && next.stroke !== 'none') {   // the dark rim of a tube
        return;
      }
      const white = lum(stroke.mid) > 0.9;
      if (white && o.op < 0.95) return;                          // soft highlight lines: the rim light does this
      if (o.op < 0.3) return;
      const prev = ops[i - 1];
      const ink = prev && prev.d === o.d && prev.stroke !== 'none' ? ramp(prev.stroke).mid : null;
      layers.push({ kind: 'stroke', subs: o.subs, r: o.sw / 2, ramp: stroke, ink, op: o.op, m: o.m, box: o.box });
    }
  });
  return layers;
}

/* ------------------------------------------------------------------ gradient shading */
const inv = m => { const det = m[0] * m[3] - m[1] * m[2]; return [m[3] / det, -m[1] / det, -m[2] / det, m[0] / det,
  (m[2] * m[5] - m[3] * m[4]) / det, (m[1] * m[4] - m[0] * m[5]) / det]; };
// where a canvas point sits along a layer's gradient (0 = first stop, 1 = last)
function gradT(L, x, y) {
  const G = L.ramp.G;
  if (!G || !L.m) return 0.5;
  const [ex, ey] = ap(inv(L.m), [x, y]);
  const [bx0, by0, bx1, by1] = L.box;
  const u = G.user ? ex : (ex - bx0) / Math.max(1e-6, bx1 - bx0), v = G.user ? ey : (ey - by0) / Math.max(1e-6, by1 - by0);
  let t;
  if (G.radial) t = Math.hypot(u - G.cx, v - G.cy) / Math.max(1e-6, G.r);
  else { const dx = G.x2 - G.x1, dy = G.y2 - G.y1; t = ((u - G.x1) * dx + (v - G.y1) * dy) / Math.max(1e-9, dx * dx + dy * dy); }
  return Math.max(0, Math.min(1, t));
}
function tone(G, t) {   // the gradient's colour at t
  const st = G.stops;
  if (t <= st[0][0]) return st[0][1];
  for (let i = 1; i < st.length; i++) if (t <= st[i][0]) return mix(st[i - 1][1], st[i][1], (t - st[i - 1][0]) / Math.max(1e-6, st[i][0] - st[i - 1][0]));
  return st[st.length - 1][1];
}

/* ------------------------------------------------------------------ rasterise */
const SS = 4;                                       // sub-samples per pixel side
function compile(svg) {
  const layers = parseSvg(svg);
  const own = Array.from({ length: N }, () => Array(N).fill(-1));     // opaque owner layer per pixel
  const tint = Array.from({ length: N }, () => Array(N).fill(null));  // translucent overlays per pixel
  layers.forEach((L, li) => {
    let best = null, painted = 0;
    const cov = [];
    let bx0 = Infinity, by0 = Infinity, bx1 = -Infinity, by1 = -Infinity;
    for (const s of L.subs) for (const [x, y] of s.pts) { bx0 = Math.min(bx0, x); by0 = Math.min(by0, y); bx1 = Math.max(bx1, x); by1 = Math.max(by1, y); }
    const pad = L.kind === 'stroke' ? L.r : 0;
    for (let py = Math.max(0, Math.floor((by0 - pad) / U)); py <= Math.min(N - 1, Math.floor((by1 + pad) / U)); py++)
      for (let px = Math.max(0, Math.floor((bx0 - pad) / U)); px <= Math.min(N - 1, Math.floor((bx1 + pad) / U)); px++) {
        let hit = 0;
        for (let j = 0; j < SS; j++) for (let i = 0; i < SS; i++) {
          const x = (px + (i + .5) / SS) * U, y = (py + (j + .5) / SS) * U;
          if (L.kind === 'fill' ? insideFill(L.subs, x, y) : nearStroke(L.subs, x, y, L.r)) hit++;
        }
        const c = hit / (SS * SS);
        if (c > 0) cov.push([px, py, c]);
        if (!best || c > best[2]) best = [px, py, c];
      }
    const need = L.kind === 'stroke' ? 0.34 : 0.5;
    const paint = (px, py) => {
      if (L.op >= 0.8) { own[py][px] = li; tint[py][px] = null; }
      else (tint[py][px] = tint[py][px] || []).push(li);
      painted++;
    };
    for (const [px, py, c] of cov) if (c >= need) paint(px, py);
    if (!painted && best && best[2] >= 0.12) paint(best[0], best[1]);   // tiny details keep one pixel
  });
  // drop specks: 1-2 pixel islands cut off from the drawing
  const filled = (x, y) => x >= 0 && y >= 0 && x < N && y < N && own[y][x] >= 0;
  const seen = new Set(), comps = [];
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    if (!filled(x, y) || seen.has(y * N + x)) continue;
    const comp = [], st = [[x, y]]; seen.add(y * N + x);
    while (st.length) {
      const [cx, cy] = st.pop(); comp.push([cx, cy]);
      for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
        const nx = cx + dx, ny = cy + dy;
        if (filled(nx, ny) && !seen.has(ny * N + nx)) { seen.add(ny * N + nx); st.push([nx, ny]); }
      }
    }
    comps.push(comp);
  }
  if (comps.some(c => c.length > 2)) for (const c of comps) if (c.length <= 2) for (const [x, y] of c) own[y][x] = -1;
  // shade each layer's region by its rim: light top/left, shadow bottom/right
  const col = Array.from({ length: N }, () => Array(N).fill(null));
  const size = {};
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) if (own[y][x] >= 0) size[own[y][x]] = (size[own[y][x]] || 0) + 1;
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const li = own[y][x]; if (li < 0) continue;
    const L = layers[li], R = L.ramp;
    if (!R.grad || size[li] < 5) { col[y][x] = R.mid; continue; }
    const same = (dx, dy) => { const nx = x + dx, ny = y + dy; return nx >= 0 && ny >= 0 && nx < N && ny < N && own[ny][nx] === li; };
    const light = !same(0, -1) || !same(-1, 0), dark = !same(0, 1) || !same(1, 0);
    let band = Math.round(gradT(L, (x + .5) * U, (y + .5) * U) * 4);
    if (light && !dark) band -= 1; else if (dark && !light) band += 1;
    if (L.kind === 'stroke') band = Math.min(band, 2);   // thin bands (rings, cords) stay bright: light to mid only
    col[y][x] = tone(R.G, Math.max(0, Math.min(4, band)) / 4);
  }
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) if (tint[y][x] && col[y][x])
    for (const li of tint[y][x]) col[y][x] = mix(col[y][x], layers[li].ramp.mid, Math.min(1, layers[li].op * 1.2));
  // parts drawn with a dark outline over another part keep that outline where they overlap it (knee guards,
  // visors, gems): the pixels of the part below that touch them take their ink
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    const li = own[y][x]; if (li < 0) continue;
    // never on the silhouette's edge: a 1-pixel rim there (shield borders) would vanish under two dark lines
    if ([[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dy]) => { const nx = x + dx, ny = y + dy; return nx < 0 || ny < 0 || nx >= N || ny >= N || own[ny][nx] < 0; })) continue;
    let rim = -1;
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || ny < 0 || nx >= N || ny >= N) continue;
      const nj = own[ny][nx];
      if (nj > li && layers[nj].rimmed && size[nj] >= 3) rim = Math.max(rim, nj);
    }
    if (rim >= 0) col[y][x] = hex(toHex(layers[rim].ink));
  }
  // one clean outline around the silhouette, in the neighbouring part's own ink
  const out = col.map(r => r.slice());
  for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) {
    if (col[y][x]) continue;
    const votes = new Map();
    for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || ny < 0 || nx >= N || ny >= N || own[ny][nx] < 0) continue;
      const L = layers[own[ny][nx]];
      const ink = toHex(L.ink || mix(L.ramp.lo, [8, 6, 12], 0.72));
      votes.set(ink, (votes.get(ink) || 0) + 1);
    }
    if (votes.size) out[y][x] = hex([...votes].sort((a, b) => b[1] - a[1])[0][0]);
  }
  return out;
}

/* ------------------------------------------------------------------ text grids */
const LETTERS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
function toTxt(name, grid) {
  const pal = new Map();
  const rows = grid.map(r => r.map(c => {
    if (!c) return '.';
    const h = toHex(c);
    if (!pal.has(h)) pal.set(h, LETTERS[pal.size]);
    return pal.get(h);
  }).join(''));
  return `# ${name}\n${MARK}\n${[...pal].map(([h, l]) => `${l} ${h}`).join('\n')}\n--\n${rows.join('\n')}\n`;
}
function fromTxt(t) {
  t = t.replace(/\r/g, '');
  const [head, body] = t.split('\n--\n');
  const pal = {};
  for (const l of head.split('\n')) { const m = l.match(/^(\S) (#[0-9a-fA-F]{6})$/); if (m) pal[m[1]] = m[2]; }
  return body.trim().split('\n').map(r => [...r].map(ch => (ch === '.' ? null : pal[ch])));
}
// Colour intensity: every icon is drawn more vivid than its grid (saturation up, a touch more contrast).
// Near-greys (steel, silver, white, outlines) keep their colour so metals are not tinted.
const VIVID = 1.3, CONTRAST = 1.08;
function vivid(h) {
  let [r, g, b] = hex(h).map(v => v / 255);
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2, d = mx - mn;
  let hue = 0, sat = 0;
  if (d) {
    sat = d / (1 - Math.abs(2 * l - 1));
    hue = mx === r ? ((g - b) / d) % 6 : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
    if (hue < 0) hue += 6;   // magentas and pinks: wrap round, or they turn orange
  }
  const s2 = sat < 0.12 ? sat : Math.min(1, sat * VIVID + 0.04);
  const l2 = Math.max(0, Math.min(1, 0.5 + (l - 0.5) * CONTRAST));
  const c = (1 - Math.abs(2 * l2 - 1)) * s2, xx = c * (1 - Math.abs((hue % 2 + 2) % 2 - 1)), m = l2 - c / 2;
  const [r1, g1, b1] = hue < 1 ? [c, xx, 0] : hue < 2 ? [xx, c, 0] : hue < 3 ? [0, c, xx] : hue < 4 ? [0, xx, c] : hue < 5 ? [xx, 0, c] : [c, 0, xx];
  return toHex([(r1 + m) * 255, (g1 + m) * 255, (b1 + m) * 255]);
}
function toSvg(grid) {
  const runs = new Map();
  grid = grid.map(r => r.map(c => (c ? vivid(c) : c)));
  grid.forEach((r, y) => { let x = 0; while (x < r.length) { const c = r[x]; if (!c) { x++; continue; } let x1 = x + 1; while (x1 < r.length && r[x1] === c) x1++; if (!runs.has(c)) runs.set(c, []); runs.get(c).push(`M${x} ${y}h${x1 - x}v1h-${x1 - x}z`); x = x1; } });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${N} ${N}" shape-rendering="crispEdges">${[...runs].map(([c, d]) => `<path fill="${c}" d="${d.join('')}"/>`).join('')}</svg>`;
}

/* ------------------------------------------------------------------ main */
const names = {};
try {
  const db = JSON.parse(readFileSync(path.join(ROOT, 'data', 'items.json'), 'utf8'));
  for (const it of db.items) names['i' + it.id] = it.name;
  for (const c of db.charms || []) names['c' + c.id] = c.name;
  for (const g of db.goods || []) names['i' + g.id] = g.name;
} catch (e) { /* names are only comments */ }

mkdirSync(SRC, { recursive: true });
const keys = readdirSync(HD).filter(f => f.endsWith('.svg')).map(f => f.replace(/\.svg$/, '')).sort();
let compiled = 0, kept = 0;
if (!process.argv.includes('--render')) {
  const only = process.argv.includes('--only') ? new Set(process.argv[process.argv.indexOf('--only') + 1].split(',')) : null;
  for (const k of keys) {
    if (only && !only.has(k)) continue;
    const file = path.join(SRC, k + '.txt');
    if (existsSync(file) && !readFileSync(file, 'utf8').includes(MARK)) { kept++; continue; }
    writeFileSync(file, toTxt(names[k] || k, compile(readFileSync(path.join(HD, k + '.svg'), 'utf8'))));
    compiled++;
  }
}
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const symbols = [];
for (const k of keys) {
  const file = path.join(SRC, k + '.txt');
  if (!existsSync(file)) continue;
  const svg = toSvg(fromTxt(readFileSync(file, 'utf8')));
  writeFileSync(path.join(OUT, k + '.svg'), svg + '\n');
  symbols.push(`<symbol id="${k}" viewBox="0 0 ${N} ${N}">${svg.slice(svg.indexOf('>') + 1, svg.lastIndexOf('</svg>'))}</symbol>`);
}
const sprite = `<svg xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges" style="display:none">${symbols.join('')}</svg>`;
writeFileSync(SPRITE, sprite);
console.log(`pixel icons: compiled ${compiled}, kept ${kept} hand-edited, rendered ${symbols.length} at ${N}x${N} (${Math.round(sprite.length / 1024)} KB sprite)`);
